version: "3.7"

services:

  traefik:
    restart: unless-stopped
    image: traefik:v2.5
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    volumes:
      - ./docker/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./docker/traefik/tls.yml:/etc/traefik/tls.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/etc/ssl/traefik

  pictsmanager_database:
    container_name: pictsmanager_database
    image: mariadb:latest
    restart: always
    command: --sql-mode="" --bind-address=0.0.0.0
    env_file:
      - ./docker/database/.env
    environment:
      - MARIADB_ROOT_PASSWORD=changeMe
      - MARIADB_USER=pictsmanager_user
      - MARIADB_PASSWORD=pictsmanager_password
      - MARIADB_DATABASE=pictsmanager_name
    volumes:
      - myslq-db:/var/lib/mysql
    labels:
      - traefik.enable=false

  phpmyadmin:
    container_name: pitcsmanager_phpmyadmin
    restart: always
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - pictsmanager_database
    env_file:
      - ./docker/phpmyadmin/.env
    labels:
      - "traefik.http.routers.api.rule=Host(`phpmyadmin.traefik.me`)"

  pictsmanager_api:
    container_name: pictsmanager_api
    image: pictsmanager:latest
    restart: always
    build:
      context: ./api
      args:
        - NODE_ENV=development
    env_file:
      - ./api/.env
    environment:
      - EXTERNAL_PORT=3000
      - MARIADB_ROOT_HOST=pictsmanager_database
    depends_on:
      - pictsmanager_database
    volumes:
      - ./api:/api
      - ./api/node_modules
    labels:
      - "traefik.http.routers.pictsmanager_api.rule=Host(`pictsmanager_api.traefik.me`)"
      - "traefik.http.routers.pictsmanager_api-tls.tls.domains[0].main=pictsmanager_api.traefik.me"
      - "traefik.http.routers.pictsmanager_api-tls.tls.domains[0].sans=pictsmanager_api-*.traefik.me"
      - "traefik.http.routers.pictsmanager_api.tls=true"

  reverse-proxy-https-helper:
    image: alpine
    command: sh -c "cd /etc/ssl/traefik && wget traefik.me/cert.pem -O cert.pem && wget traefik.me/privkey.pem -O privkey.pem"
    volumes:
      - certs:/etc/ssl/traefik

volumes:
  myslq-db:
  certs:
