name: Build Container for Prod and Push to Dockerhub

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-deploy-back:
    runs-on: ubuntu-latest
    steps:
      - name: Install Action
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v1


        # - name: Build and push Docker image
        #   uses: docker/build-push-action@v1
        #   with:
        #     username: ${{ secrets.DOCKER_USERNAME }}
        #     password: ${{ secrets.DOCKER_PASSWORD }}
        #     repository: Dkalumvuati/pictsmanager
        #     dockerfile: duramana/pictsmanager
        #     tags: latest
  publish:
    runs-on: ubuntu-latest
    needs: [ build-and-deploy-back]